# Generated by Django 4.2.3 on 2023-08-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoralo_app', '0002_remove_pelicula_valoracion_valoracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.IntegerField(default=0),
        ),
    ]
