# Generated by Django 4.2.3 on 2023-08-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valoralo_app', '0007_valoracion_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='pelicula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='valoralo_app.pelicula'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='valoraciones',
            field=models.ManyToManyField(related_name='peliculas_valoradas', to='valoralo_app.valoracion'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
