# Generated by Django 4.2.3 on 2023-08-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoralo_app', '0008_valoracion_pelicula_alter_pelicula_valoraciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
