# Generated by Django 4.2.3 on 2023-09-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoralo_app', '0009_alter_valoracion_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='promedio',
            field=models.FloatField(default=0),
        ),
    ]
