# Generated by Django 4.2.3 on 2023-09-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoralo_app', '0010_pelicula_cantidad_pelicula_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='promedio',
            field=models.FloatField(default=0, null=True),
        ),
    ]
