# Generated by Django 4.2.3 on 2023-09-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoralo_app', '0011_alter_pelicula_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='promedio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
